# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

version: '3.8'

services:
  nats-server:
    image: nats
    command: ["-js", "--trace"]
    ports:
      - 4222:4222
      - 6222:6222
      - 8222:8222

  etcd-server:
    image: bitnami/etcd
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
    ports:
      - 2379:2379
      - 2380:2380

  dynamo-llm:
    image: dynamo-cuda-12.5.1-ubuntu24.04
    runtime: nvidia
    command: ["dynamo", "serve", "graphs.agg:Frontend", "-f", "configs/agg_qwen_1.5B.yaml"]
    ipc: host
    working_dir: /app/examples/llm
    volumes:
      - ../models:/root/.cache
      - ./examples:/app/examples
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - ETCD_ENDPOINTS=http://etcd-server:2379
      - NATS_SERVER=nats://nats-server:4222
    depends_on:
      - nats-server
      - etcd-server
    ports:
      - 8000:8000

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./metrics/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    network_mode: "host"
    profiles: [metrics]

  grafana:
    image: grafana/grafana-enterprise:latest
    container_name: grafana
    volumes:
      - ./metrics/grafana.json:/etc/grafana/provisioning/dashboards/llm-worker-dashboard.json
      - ./metrics/grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - ./metrics/grafana-dashboard-providers.yml:/etc/grafana/provisioning/dashboards/dashboard-providers.yml
    environment:
      - GF_SERVER_HTTP_PORT=3001
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
      - GF_DASHBOARDS_MIN_REFRESH_INTERVAL=2s
    restart: unless-stopped
    network_mode: "host"
    profiles: [metrics]
    depends_on:
      - prometheus